on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore & Build
        run: msbuild PianoTilesRedux.Desktop.slnf /restore -warnaserror -p:Configuration=Debug

  test:
    name: Test
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore & Build
        run: msbuild PianoTilesRedux.Desktop.slnf /restore -warnaserror -p:Configuration=Debug

      - name: Test
        run: dotnet test $pwd/**/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-Windows.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PianoTilesRedux-TestResults-Windows
          path: ${{github.workspace}}/TestResults/TestResults-Windows.trx

  build-only-android:
    name: Build only (Android)
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore & Build
        run: msbuild PianoTilesRedux.Android/PianoTilesRedux.Android.csproj /restore -warnaserror -p:Configuration=Debug

  build-only-ios:
    name: Build only (iOS)
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore & Build
        run: msbuild PianoTilesRedux.iOS/PianoTilesRedux.iOS.csproj /restore -warnaserror -p:Configuration=Debug
